version: 2.1

orbs:
  win: circleci/windows@2.2.0
  github-release: haskell-works/github-release@1.3.3

jobs:
  build:
    executor: win/default     

    steps:
    - checkout
    - run:
        name: "publish and create artifact"
        command: |
          msbuild -restore -t:publish -p:Configuration=Release Src/ServerGridEditor.sln
          Compress-Archive C:\Users\circleci\project\build\net472\publish\* SGE.zip
    - store_artifacts:
        path: SGE.zip

  release:
    executor: github-release/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: version number
          command: |
            echo "export BUILD_VERSION=\"${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}\"" | tee -a $BASH_ENV
      - github-release/release:
          tag: v$BUILD_VERSION
          title: $BUILD_VERSION
          artefacts-folder: .